// <auto-generated />
using System;
using MangoTaikaDistrict.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangoTaikaDistrict.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116055931_AddMfaCompetencesAndLivreOrPage")]
    partial class AddMfaCompetencesAndLivreOrPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Activite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lieu")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeActivite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GroupeId");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Actualite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Actualites");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Visibilite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.AscciStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateVerification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroCarte")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifieParId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScoutId");

                    b.HasIndex("VerifieParId");

                    b.ToTable("AscciStatuses");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Assurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Compagnie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoutId");

                    b.ToTable("Assurances");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CarteScout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateEmission")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoutId");

                    b.ToTable("CartesScout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Certificat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmisParId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstValide")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InscriptionFormationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroCertificat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlCertificat")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmisParId");

                    b.HasIndex("InscriptionFormationId");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CircuitEtape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CircuitValidationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleRequis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CircuitValidationId");

                    b.ToTable("CircuitEtapes");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CircuitValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CircuitsValidation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Consentement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Consentements");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Cotisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnregistrement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnregistreParId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontantAttendu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("numeric");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnregistreParId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("ScoutId");

                    b.ToTable("Cotisations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.DemandeAutorisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiviteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActiviteId")
                        .IsUnique();

                    b.HasIndex("DemandeurId");

                    b.ToTable("DemandesAutorisation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.DemandeDroitRgpd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Raison")
                        .HasColumnType("text");

                    b.Property<string>("Reponse")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TraiteLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TraiteParId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TraiteParId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("DemandesDroitRgpd");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DureeEstimee")
                        .HasColumnType("integer");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstPublique")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Groupe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactTel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GpsLat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GpsLng")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.InscriptionFormation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCompletion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NoteFinale")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("ScoutId");

                    b.ToTable("InscriptionsFormation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.LivreOrMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedById");

                    b.ToTable("LivreOr");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.LivreOrPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LivreOrPages");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ModuleFormation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenu")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<int>("DureeEstimee")
                        .HasColumnType("integer");

                    b.Property<bool>("EstObligatoire")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("ModulesFormation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.MotCommissaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("MotsCommissaire");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Nomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutoriteValidationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreeParId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<string>("Fonction")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutoriteValidationId");

                    b.HasIndex("CreeParId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("ScoutId");

                    b.ToTable("Nominations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ParentScout", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParentId", "ScoutId");

                    b.HasIndex("ScoutId");

                    b.ToTable("ParentScouts");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ProgressionModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateCompletion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InscriptionFormationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleFormationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Note")
                        .HasColumnType("numeric");

                    b.Property<int>("TempsConsacre")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InscriptionFormationId");

                    b.HasIndex("ModuleFormationId");

                    b.ToTable("ProgressionsModule");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Scout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<decimal?>("GpsLat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GpsLng")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("text");

                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexe")
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UniteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("UniteId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Scouts");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ScoutCompetence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificatUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("CompetenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateAcquisition")
                        .HasColumnType("date");

                    b.Property<string>("Niveau")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScoutId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.HasIndex("ScoutId");

                    b.HasIndex("ScoutId1");

                    b.ToTable("ScoutCompetences");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Unite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branche")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("Unites");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ValidatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Telephone")
                        .IsUnique();

                    b.HasIndex("ValidatedById");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.UtilisateurRole", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UtilisateurId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UtilisateurRoles");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Validation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("DemandeAutorisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ValideurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DemandeAutorisationId");

                    b.HasIndex("ValideurId");

                    b.ToTable("Validations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ValidationNomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("NominationId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ValideurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NominationId");

                    b.HasIndex("ValideurId");

                    b.ToTable("ValidationsNomination");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Activite", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Activites")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Actualite", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.AscciStatus", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany()
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "VerifiePar")
                        .WithMany()
                        .HasForeignKey("VerifieParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scout");

                    b.Navigation("VerifiePar");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Assurance", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany("Assurances")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CarteScout", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany("Cartes")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Certificat", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "EmisPar")
                        .WithMany()
                        .HasForeignKey("EmisParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.InscriptionFormation", "InscriptionFormation")
                        .WithMany("Certificats")
                        .HasForeignKey("InscriptionFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmisPar");

                    b.Navigation("InscriptionFormation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CircuitEtape", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.CircuitValidation", "CircuitValidation")
                        .WithMany("Etapes")
                        .HasForeignKey("CircuitValidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircuitValidation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Consentement", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Cotisation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "EnregistrePar")
                        .WithMany()
                        .HasForeignKey("EnregistreParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Cotisations")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany("Cotisations")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnregistrePar");

                    b.Navigation("Groupe");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.DemandeAutorisation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Activite", "Activite")
                        .WithOne("DemandeAutorisation")
                        .HasForeignKey("MangoTaikaDistrict.Domain.Entities.DemandeAutorisation", "ActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Demandeur")
                        .WithMany()
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activite");

                    b.Navigation("Demandeur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.DemandeDroitRgpd", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "TraitePar")
                        .WithMany()
                        .HasForeignKey("TraiteParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("DemandesDroitRgpd")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraitePar");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Document", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Formation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.InscriptionFormation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Formation", "Formation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany()
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.LivreOrMessage", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "ModeratedBy")
                        .WithMany()
                        .HasForeignKey("ModeratedById");

                    b.Navigation("ModeratedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Media", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Album", "Album")
                        .WithMany("Medias")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ModuleFormation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Formation", "Formation")
                        .WithMany("Modules")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.MotCommissaire", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Nomination", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "AutoriteValidation")
                        .WithMany()
                        .HasForeignKey("AutoriteValidationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreePar")
                        .WithMany()
                        .HasForeignKey("CreeParId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Nominations")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany("Nominations")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AutoriteValidation");

                    b.Navigation("CreePar");

                    b.Navigation("Groupe");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Parent", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ParentScout", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Parent", "Parent")
                        .WithMany("ParentScouts")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany()
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ProgressionModule", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.InscriptionFormation", "InscriptionFormation")
                        .WithMany("Progressions")
                        .HasForeignKey("InscriptionFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.ModuleFormation", "ModuleFormation")
                        .WithMany("Progressions")
                        .HasForeignKey("ModuleFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscriptionFormation");

                    b.Navigation("ModuleFormation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Scout", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Scouts")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Unite", "Unite")
                        .WithMany("Scouts")
                        .HasForeignKey("UniteId");

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Scouts")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Groupe");

                    b.Navigation("Unite");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ScoutCompetence", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Competence", "Competence")
                        .WithMany("ScoutCompetences")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", "Scout")
                        .WithMany()
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Scout", null)
                        .WithMany("ScoutCompetences")
                        .HasForeignKey("ScoutId1");

                    b.Navigation("Competence");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Unite", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Groupe", "Groupe")
                        .WithMany("Unites")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Utilisateur", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "ValidatedBy")
                        .WithMany()
                        .HasForeignKey("ValidatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ValidatedBy");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.UtilisateurRole", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("UtilisateurRoles")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Validation", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.DemandeAutorisation", "DemandeAutorisation")
                        .WithMany("Validations")
                        .HasForeignKey("DemandeAutorisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandeAutorisation");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ValidationNomination", b =>
                {
                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Nomination", "Nomination")
                        .WithMany("Validations")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangoTaikaDistrict.Domain.Entities.Utilisateur", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nomination");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Activite", b =>
                {
                    b.Navigation("DemandeAutorisation");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Album", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.CircuitValidation", b =>
                {
                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Competence", b =>
                {
                    b.Navigation("ScoutCompetences");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.DemandeAutorisation", b =>
                {
                    b.Navigation("Validations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Formation", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Groupe", b =>
                {
                    b.Navigation("Activites");

                    b.Navigation("Cotisations");

                    b.Navigation("Nominations");

                    b.Navigation("Scouts");

                    b.Navigation("Unites");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.InscriptionFormation", b =>
                {
                    b.Navigation("Certificats");

                    b.Navigation("Progressions");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.ModuleFormation", b =>
                {
                    b.Navigation("Progressions");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Nomination", b =>
                {
                    b.Navigation("Validations");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Parent", b =>
                {
                    b.Navigation("ParentScouts");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Scout", b =>
                {
                    b.Navigation("Assurances");

                    b.Navigation("Cartes");

                    b.Navigation("Cotisations");

                    b.Navigation("Nominations");

                    b.Navigation("ScoutCompetences");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Unite", b =>
                {
                    b.Navigation("Scouts");
                });

            modelBuilder.Entity("MangoTaikaDistrict.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("DemandesDroitRgpd");

                    b.Navigation("Scouts");

                    b.Navigation("UtilisateurRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
